apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fluxcd-repo
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://github.com/pguniganti/FluxCD
  ref:
    branch: main
  secretRef:
    name: git-credentials
