apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/pguniganti/FluxCD
  ref:
    branch: main
  secretRef:
    name: flux-system
