apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: default
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: GitRepository
        name: fluxcd-repo
  values:
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: aws-ebs-gp2
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 40Gi
    alertmanager:
      alertmanagerSpec:
        replicas: 2
    grafana:
      adminPassword: "prom-operator"
